### ISSUE TITLE
bash command not found

### ISSUE THREAD

**Issue by ghost** [NubeDev/sedonadev#1]
I'm not sure if I'm making a mistake on the bash --rcfile unix/init.sh or the makeunixdev step but whenever I try to compile this I constantly get this error

bash: makeunixdev.py: command not found

I've tried this running arch linux and also raspian jessie.

Any suggestions?  Or somewhere I could download a zip file of sedona already compiled?

Thanks

**Comment by NubeDev** [comment]
Hey mate,
I haven't touch this in around 6 months but ill try and help.
Dont worry about arch i just used raspian. 
This tested and work on Raspberry Pi 2 ARM Cortex-A7
Are you trying to build on the PI?
Ill update the readme with my old notes as what is there now i think was the default from the sedona-dev website.

**Comment by NubeDev** [comment]
If that didn't help you i do have a complied version somewhere but its not production ready. Let me know if you want it

**Comment by ghost** [comment]
I still cannot get it to work.  It must be something in the latest version of raspian or I'm doing something wrong since I'm still new to all of this.  If you have a compiled version,that would be great.  I had questions on your bacnet node red as well, but it's too early this morning to remember what they were.  
The reason for all of this is I'm trying to find a way to connect IoT devices and node red functions to my personal niagara server for my home automation.  I'm a systems integrator by day so I deal with niagara and sedona devices at work, but I'm using node red at home to tinker around.  Other than modbus I have yet to find a good working bridge between the two worlds.  Your sedona MQTT seemed like a good option since I have a pile of raspberry pi's around the house.

**Comment by NubeDev** [comment]
Oh ok well its actually quite easy then to read and write from Niagara by using Obix.
Add the obix driver in workbench and go to www.yournigara.com/obix
Then in node-red do http get and http put into the points and history's

**Comment by ghost** [comment]
How do you handle the niagara login on the node red side

**Comment by NubeDev** [comment]
Here is a flow example. But make sure you do the following
- Add obix driver
- In browser make sure you can see the xml after you login at www.yourAX.com/obix
- Depending on what version of Niagara you have you may have to adjust the user secuirty setting


[{"id":"15bef605.c5e97a","type":"function","z":"44dfa155.b4ab","name":"Convert the credentials in base64","func":"msg.obixAuth = Buffer.from(\"enter_username:enter_passowrd\").toString(\"base64\");\nreturn msg;","outputs":1,"noerr":0,"x":438,"y":208,"wires":[["cf0bfee.b070c"]]},{"id":"36643145.21852e","type":"inject","z":"44dfa155.b4ab","name":"Trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":351,"y":112,"wires":[["15bef605.c5e97a"]]},{"id":"cf0bfee.b070c","type":"function","z":"44dfa155.b4ab","name":"Configure request options","func":"msg = {\n \"method\": \"GET\",\n \"url\": \"http://YOUR_URL/obix/histories/\",\n \"headers\": {\n \"Authorization\": \"Basic \" + msg.obixAuth,\n \"Accept\": \"*/*\"\n }\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":428,"y":322,"wires":[["88b322e0.93cc6","50573b1d.f54904"]]},{"id":"88b322e0.93cc6","type":"http request","z":"44dfa155.b4ab","name":"URL List request","method":"use","ret":"txt","url":"","tls":"","x":735,"y":267,"wires":[["1bf7e948.4a39f7","83d3f5be.2e5868","bb4a6784.727bc8"]]},{"id":"bb4a6784.727bc8","type":"debug","z":"44dfa155.b4ab","name":"","active":true,"console":"false","complete":"false","x":975,"y":259,"wires":[]},{"id":"1641309e.36800f","type":"inject","z":"44dfa155.b4ab","name":"Trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":416,"y":595,"wires":[["9a1da28d.f51e4"]]},{"id":"9a1da28d.f51e4","type":"http request","z":"44dfa155.b4ab","name":"URL List request","method":"GET","ret":"txt","url":"http://YOUR_URL/obix/histories/","tls":"","x":645,"y":594,"wires":[["1bf7e948.4a39f7","83d3f5be.2e5868","98f0ffc5.1c192"]]},{"id":"98f0ffc5.1c192","type":"debug","z":"44dfa155.b4ab","name":"","active":true,"console":"false","complete":"false","x":885,"y":586,"wires":[]},{"id":"9e73a8c7.855aa8","type":"comment","z":"44dfa155.b4ab","name":"enter user details","info":"","x":459,"y":167,"wires":[]},{"id":"e768a1ad.43d1","type":"comment","z":"44dfa155.b4ab","name":"enter URL details","info":"","x":439,"y":283,"wires":[]},{"id":"21c88c91.954514","type":"comment","z":"44dfa155.b4ab","name":"enter URL and user details","info":"","x":655,"y":553,"wires":[]},{"id":"5cb0f46f.650bfc","type":"comment","z":"44dfa155.b4ab","name":"Obix option 1","info":"","x":734,"y":224,"wires":[]},{"id":"be240fe8.04171","type":"comment","z":"44dfa155.b4ab","name":"Obix option 2","info":"","x":704,"y":467,"wires":[]}]

**Comment by ghost** [comment]
Now I'm really doing something wrong.  I cannot get that flow to import for some reason.  I'll try to read over the format and convert it.

**Comment by NubeDev** [comment]
[
    {
        "id": "44dfa155.b4ab",
        "type": "tab",
        "label": "Flow 15"
    },
    {
        "id": "15bef605.c5e97a",
        "type": "function",
        "z": "44dfa155.b4ab",
        "name": "Convert the credentials in base64",
        "func": "msg.obixAuth = Buffer.from(\"enter_username:enter_passowrd\").toString(\"base64\");\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 438,
        "y": 208,
        "wires": [
            [
                "cf0bfee.b070c"
            ]
        ]
    },
    {
        "id": "36643145.21852e",
        "type": "inject",
        "z": "44dfa155.b4ab",
        "name": "Trigger",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 351,
        "y": 112,
        "wires": [
            [
                "15bef605.c5e97a"
            ]
        ]
    },
    {
        "id": "cf0bfee.b070c",
        "type": "function",
        "z": "44dfa155.b4ab",
        "name": "Configure request options",
        "func": "msg = {\n \"method\": \"GET\",\n \"url\": \"http://YOUR_URL/obix/histories/\",\n \"headers\": {\n \"Authorization\": \"Basic \" + msg.obixAuth,\n \"Accept\": \"*/*\"\n }\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 428,
        "y": 322,
        "wires": [
            [
                "88b322e0.93cc6",
                "50573b1d.f54904"
            ]
        ]
    },
    {
        "id": "88b322e0.93cc6",
        "type": "http request",
        "z": "44dfa155.b4ab",
        "name": "URL List request",
        "method": "use",
        "ret": "txt",
        "url": "",
        "tls": "",
        "x": 735,
        "y": 267,
        "wires": [
            [
                "1bf7e948.4a39f7",
                "83d3f5be.2e5868",
                "bb4a6784.727bc8"
            ]
        ]
    },
    {
        "id": "bb4a6784.727bc8",
        "type": "debug",
        "z": "44dfa155.b4ab",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 975,
        "y": 259,
        "wires": []
    },
    {
        "id": "1641309e.36800f",
        "type": "inject",
        "z": "44dfa155.b4ab",
        "name": "Trigger",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 416,
        "y": 595,
        "wires": [
            [
                "9a1da28d.f51e4"
            ]
        ]
    },
    {
        "id": "9a1da28d.f51e4",
        "type": "http request",
        "z": "44dfa155.b4ab",
        "name": "URL List request",
        "method": "GET",
        "ret": "txt",
        "url": "http://YOUR_URL/obix/histories/",
        "tls": "",
        "x": 645,
        "y": 594,
        "wires": [
            [
                "1bf7e948.4a39f7",
                "83d3f5be.2e5868",
                "98f0ffc5.1c192"
            ]
        ]
    },
    {
        "id": "98f0ffc5.1c192",
        "type": "debug",
        "z": "44dfa155.b4ab",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 885,
        "y": 586,
        "wires": []
    },
    {
        "id": "9e73a8c7.855aa8",
        "type": "comment",
        "z": "44dfa155.b4ab",
        "name": "enter user details",
        "info": "",
        "x": 459,
        "y": 167,
        "wires": []
    },
    {
        "id": "e768a1ad.43d1",
        "type": "comment",
        "z": "44dfa155.b4ab",
        "name": "enter URL details",
        "info": "",
        "x": 439,
        "y": 283,
        "wires": []
    },
    {
        "id": "21c88c91.954514",
        "type": "comment",
        "z": "44dfa155.b4ab",
        "name": "enter URL and user details",
        "info": "",
        "x": 655,
        "y": 553,
        "wires": []
    },
    {
        "id": "5cb0f46f.650bfc",
        "type": "comment",
        "z": "44dfa155.b4ab",
        "name": "Obix option 1",
        "info": "",
        "x": 734,
        "y": 224,
        "wires": []
    },
    {
        "id": "be240fe8.04171",
        "type": "comment",
        "z": "44dfa155.b4ab",
        "name": "Obix option 2",
        "info": "",
        "x": 704,
        "y": 467,
        "wires": []
    }
]

**Comment by NubeDev** [comment]
Its not you it was github.

`[{"id":"ac12b1e6.0f482","type":"tab","label":"Flow 15"},{"id":"8af6f73f.39c648","type":"function","z":"ac12b1e6.0f482","name":"Convert the credentials in base64","func":"msg.obixAuth = Buffer.from(\"enter_username:enter_passowrd\").toString(\"base64\");\nreturn msg;","outputs":1,"noerr":0,"x":438,"y":208,"wires":[["7ad4de88.600ad"]]},{"id":"517d60e2.a688a","type":"inject","z":"ac12b1e6.0f482","name":"Trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":351,"y":112,"wires":[["8af6f73f.39c648"]]},{"id":"7ad4de88.600ad","type":"function","z":"ac12b1e6.0f482","name":"Configure request options","func":"msg = {\n \"method\": \"GET\",\n \"url\": \"http://YOUR_URL/obix/histories/\",\n \"headers\": {\n \"Authorization\": \"Basic \" + msg.obixAuth,\n \"Accept\": \"*/*\"\n }\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":428,"y":322,"wires":[["5cc7c3a1.37599c","50573b1d.f54904"]]},{"id":"5cc7c3a1.37599c","type":"http request","z":"ac12b1e6.0f482","name":"URL List request","method":"use","ret":"txt","url":"","tls":"","x":735,"y":267,"wires":[["1bf7e948.4a39f7","83d3f5be.2e5868","12e75096.09cf8f"]]},{"id":"12e75096.09cf8f","type":"debug","z":"ac12b1e6.0f482","name":"","active":true,"console":"false","complete":"false","x":975,"y":259,"wires":[]},{"id":"6be49873.9ac9e8","type":"inject","z":"ac12b1e6.0f482","name":"Trigger","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":416,"y":595,"wires":[["a7aed323.ac99"]]},{"id":"a7aed323.ac99","type":"http request","z":"ac12b1e6.0f482","name":"URL List request","method":"GET","ret":"txt","url":"http://YOUR_URL/obix/histories/","tls":"","x":645,"y":594,"wires":[["1bf7e948.4a39f7","83d3f5be.2e5868","498e0998.c2c128"]]},{"id":"498e0998.c2c128","type":"debug","z":"ac12b1e6.0f482","name":"","active":true,"console":"false","complete":"false","x":885,"y":586,"wires":[]},{"id":"17ebd4f3.be70eb","type":"comment","z":"ac12b1e6.0f482","name":"enter user details","info":"","x":459,"y":167,"wires":[]},{"id":"6a83473b.817f58","type":"comment","z":"ac12b1e6.0f482","name":"enter URL details","info":"","x":439,"y":283,"wires":[]},{"id":"ff294358.868db","type":"comment","z":"ac12b1e6.0f482","name":"enter URL and user details","info":"","x":655,"y":553,"wires":[]},{"id":"9a730f6.b112ff","type":"comment","z":"ac12b1e6.0f482","name":"Obix option 1","info":"","x":734,"y":224,"wires":[]},{"id":"1a166220.e47e7e","type":"comment","z":"ac12b1e6.0f482","name":"Obix option 2","info":"","x":704,"y":467,"wires":[]}]`

**Comment by ghost** [comment]
Thanks for that.  I'll give that a try.

**Comment by ghost** [comment]
Ok, I'm back again for round 2.  Your obix to node red works perfectly in Ax, but I haven't fiddled with N4 yet, maybe this weekend since that is my target platform.  
Back to the raspberry pi.  I've succeeded finally in getting the MQTT and BACnet running in sedona on my pi, but now I'm lost on setting up the GPIO.  I hate to keep bugging you about this but my google fu is weak on this subject.  Is there a dummies guide somewhere on how to use the inputs.  I'm trying to take a digital input and pass it to BACnet.
Thanks

**Comment by NubeDev** [comment]
No problems the sedona GPIO work kind off stopped before being tested well. There is an i2c driver in that sedona code somewhere. 
Do you want some code to use BACnet/ip GPIO on a raspberry pi? If so i did some testing about 1 year ago if you want i can dig up my notes but this is coded in C.
With N4 you need to create a user and change the authentication to "ax digest" but could be wrong i tested it about 1 year ago.

On sedona!
In my option sedona kinda sucks and has no active community at all. So as far as im concerned as a project its dead that's why i moved on plus our friends at Trdium are not updating there framework with the Sedona driver. 

But with node-red its kinda cool as its JavaScript and has an active community and MQTT is about 1000 times more efficient then BACnet so we are doing a lot of work in that area.

**Comment by nairn** [comment]
Hi guys do either of you have a working possible SD card image of this running on your PI2/3, I'm struggling big time to get it to run. would really appreciate if someone could give a link to an image of the SD if either of you have the time, alternatively I can provide a one drive link. would really appreciate it have a project trying to complete and this would help me a lot.
